#configuration file
theme: jekyll-theme-architect
#baseurl: "/Website" # the subpath of your site, e.g. /blog
#url: "https://github.jaypeegithub.com" # the base hostname & protocol for your site, e.g. http://example.com
